"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PROTOCOL_VERSION = exports.ProtocolSchemas = void 0;
var agent_js_1 = require("./agent.js");
var agents_models_skills_js_1 = require("./agents-models-skills.js");
var channels_js_1 = require("./channels.js");
var config_js_1 = require("./config.js");
var cron_js_1 = require("./cron.js");
var exec_approvals_js_1 = require("./exec-approvals.js");
var devices_js_1 = require("./devices.js");
var frames_js_1 = require("./frames.js");
var logs_chat_js_1 = require("./logs-chat.js");
var nodes_js_1 = require("./nodes.js");
var sessions_js_1 = require("./sessions.js");
var snapshot_js_1 = require("./snapshot.js");
var wizard_js_1 = require("./wizard.js");
exports.ProtocolSchemas = {
  ConnectParams: frames_js_1.ConnectParamsSchema,
  HelloOk: frames_js_1.HelloOkSchema,
  RequestFrame: frames_js_1.RequestFrameSchema,
  ResponseFrame: frames_js_1.ResponseFrameSchema,
  EventFrame: frames_js_1.EventFrameSchema,
  GatewayFrame: frames_js_1.GatewayFrameSchema,
  PresenceEntry: snapshot_js_1.PresenceEntrySchema,
  StateVersion: snapshot_js_1.StateVersionSchema,
  Snapshot: snapshot_js_1.SnapshotSchema,
  ErrorShape: frames_js_1.ErrorShapeSchema,
  AgentEvent: agent_js_1.AgentEventSchema,
  SendParams: agent_js_1.SendParamsSchema,
  PollParams: agent_js_1.PollParamsSchema,
  AgentParams: agent_js_1.AgentParamsSchema,
  AgentIdentityParams: agent_js_1.AgentIdentityParamsSchema,
  AgentIdentityResult: agent_js_1.AgentIdentityResultSchema,
  AgentWaitParams: agent_js_1.AgentWaitParamsSchema,
  WakeParams: agent_js_1.WakeParamsSchema,
  NodePairRequestParams: nodes_js_1.NodePairRequestParamsSchema,
  NodePairListParams: nodes_js_1.NodePairListParamsSchema,
  NodePairApproveParams: nodes_js_1.NodePairApproveParamsSchema,
  NodePairRejectParams: nodes_js_1.NodePairRejectParamsSchema,
  NodePairVerifyParams: nodes_js_1.NodePairVerifyParamsSchema,
  NodeRenameParams: nodes_js_1.NodeRenameParamsSchema,
  NodeListParams: nodes_js_1.NodeListParamsSchema,
  NodeDescribeParams: nodes_js_1.NodeDescribeParamsSchema,
  NodeInvokeParams: nodes_js_1.NodeInvokeParamsSchema,
  NodeInvokeResultParams: nodes_js_1.NodeInvokeResultParamsSchema,
  NodeEventParams: nodes_js_1.NodeEventParamsSchema,
  NodeInvokeRequestEvent: nodes_js_1.NodeInvokeRequestEventSchema,
  SessionsListParams: sessions_js_1.SessionsListParamsSchema,
  SessionsPreviewParams: sessions_js_1.SessionsPreviewParamsSchema,
  SessionsResolveParams: sessions_js_1.SessionsResolveParamsSchema,
  SessionsPatchParams: sessions_js_1.SessionsPatchParamsSchema,
  SessionsResetParams: sessions_js_1.SessionsResetParamsSchema,
  SessionsDeleteParams: sessions_js_1.SessionsDeleteParamsSchema,
  SessionsCompactParams: sessions_js_1.SessionsCompactParamsSchema,
  ConfigGetParams: config_js_1.ConfigGetParamsSchema,
  ConfigSetParams: config_js_1.ConfigSetParamsSchema,
  ConfigApplyParams: config_js_1.ConfigApplyParamsSchema,
  ConfigPatchParams: config_js_1.ConfigPatchParamsSchema,
  ConfigSchemaParams: config_js_1.ConfigSchemaParamsSchema,
  ConfigSchemaResponse: config_js_1.ConfigSchemaResponseSchema,
  WizardStartParams: wizard_js_1.WizardStartParamsSchema,
  WizardNextParams: wizard_js_1.WizardNextParamsSchema,
  WizardCancelParams: wizard_js_1.WizardCancelParamsSchema,
  WizardStatusParams: wizard_js_1.WizardStatusParamsSchema,
  WizardStep: wizard_js_1.WizardStepSchema,
  WizardNextResult: wizard_js_1.WizardNextResultSchema,
  WizardStartResult: wizard_js_1.WizardStartResultSchema,
  WizardStatusResult: wizard_js_1.WizardStatusResultSchema,
  TalkModeParams: channels_js_1.TalkModeParamsSchema,
  ChannelsStatusParams: channels_js_1.ChannelsStatusParamsSchema,
  ChannelsStatusResult: channels_js_1.ChannelsStatusResultSchema,
  ChannelsLogoutParams: channels_js_1.ChannelsLogoutParamsSchema,
  WebLoginStartParams: channels_js_1.WebLoginStartParamsSchema,
  WebLoginWaitParams: channels_js_1.WebLoginWaitParamsSchema,
  AgentSummary: agents_models_skills_js_1.AgentSummarySchema,
  AgentsListParams: agents_models_skills_js_1.AgentsListParamsSchema,
  AgentsListResult: agents_models_skills_js_1.AgentsListResultSchema,
  ModelChoice: agents_models_skills_js_1.ModelChoiceSchema,
  ModelsListParams: agents_models_skills_js_1.ModelsListParamsSchema,
  ModelsListResult: agents_models_skills_js_1.ModelsListResultSchema,
  SkillsStatusParams: agents_models_skills_js_1.SkillsStatusParamsSchema,
  SkillsBinsParams: agents_models_skills_js_1.SkillsBinsParamsSchema,
  SkillsBinsResult: agents_models_skills_js_1.SkillsBinsResultSchema,
  SkillsInstallParams: agents_models_skills_js_1.SkillsInstallParamsSchema,
  SkillsUpdateParams: agents_models_skills_js_1.SkillsUpdateParamsSchema,
  CronJob: cron_js_1.CronJobSchema,
  CronListParams: cron_js_1.CronListParamsSchema,
  CronStatusParams: cron_js_1.CronStatusParamsSchema,
  CronAddParams: cron_js_1.CronAddParamsSchema,
  CronUpdateParams: cron_js_1.CronUpdateParamsSchema,
  CronRemoveParams: cron_js_1.CronRemoveParamsSchema,
  CronRunParams: cron_js_1.CronRunParamsSchema,
  CronRunsParams: cron_js_1.CronRunsParamsSchema,
  CronRunLogEntry: cron_js_1.CronRunLogEntrySchema,
  LogsTailParams: logs_chat_js_1.LogsTailParamsSchema,
  LogsTailResult: logs_chat_js_1.LogsTailResultSchema,
  ExecApprovalsGetParams: exec_approvals_js_1.ExecApprovalsGetParamsSchema,
  ExecApprovalsSetParams: exec_approvals_js_1.ExecApprovalsSetParamsSchema,
  ExecApprovalsNodeGetParams: exec_approvals_js_1.ExecApprovalsNodeGetParamsSchema,
  ExecApprovalsNodeSetParams: exec_approvals_js_1.ExecApprovalsNodeSetParamsSchema,
  ExecApprovalsSnapshot: exec_approvals_js_1.ExecApprovalsSnapshotSchema,
  ExecApprovalRequestParams: exec_approvals_js_1.ExecApprovalRequestParamsSchema,
  ExecApprovalResolveParams: exec_approvals_js_1.ExecApprovalResolveParamsSchema,
  DevicePairListParams: devices_js_1.DevicePairListParamsSchema,
  DevicePairApproveParams: devices_js_1.DevicePairApproveParamsSchema,
  DevicePairRejectParams: devices_js_1.DevicePairRejectParamsSchema,
  DeviceTokenRotateParams: devices_js_1.DeviceTokenRotateParamsSchema,
  DeviceTokenRevokeParams: devices_js_1.DeviceTokenRevokeParamsSchema,
  DevicePairRequestedEvent: devices_js_1.DevicePairRequestedEventSchema,
  DevicePairResolvedEvent: devices_js_1.DevicePairResolvedEventSchema,
  ChatHistoryParams: logs_chat_js_1.ChatHistoryParamsSchema,
  ChatSendParams: logs_chat_js_1.ChatSendParamsSchema,
  ChatAbortParams: logs_chat_js_1.ChatAbortParamsSchema,
  ChatInjectParams: logs_chat_js_1.ChatInjectParamsSchema,
  ChatEvent: logs_chat_js_1.ChatEventSchema,
  UpdateRunParams: config_js_1.UpdateRunParamsSchema,
  TickEvent: frames_js_1.TickEventSchema,
  ShutdownEvent: frames_js_1.ShutdownEventSchema,
};
exports.PROTOCOL_VERSION = 3;
