"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DEFAULT_AI_SNAPSHOT_EFFICIENT_DEPTH =
  exports.DEFAULT_AI_SNAPSHOT_EFFICIENT_MAX_CHARS =
  exports.DEFAULT_AI_SNAPSHOT_MAX_CHARS =
  exports.DEFAULT_BROWSER_DEFAULT_PROFILE_NAME =
  exports.DEFAULT_OPENCLAW_BROWSER_PROFILE_NAME =
  exports.DEFAULT_OPENCLAW_BROWSER_COLOR =
  exports.DEFAULT_BROWSER_EVALUATE_ENABLED =
  exports.DEFAULT_OPENCLAW_BROWSER_ENABLED =
    void 0;
exports.DEFAULT_OPENCLAW_BROWSER_ENABLED = true;
exports.DEFAULT_BROWSER_EVALUATE_ENABLED = true;
exports.DEFAULT_OPENCLAW_BROWSER_COLOR = "#FF4500";
exports.DEFAULT_OPENCLAW_BROWSER_PROFILE_NAME = "openclaw";
exports.DEFAULT_BROWSER_DEFAULT_PROFILE_NAME = "chrome";
exports.DEFAULT_AI_SNAPSHOT_MAX_CHARS = 80000;
exports.DEFAULT_AI_SNAPSHOT_EFFICIENT_MAX_CHARS = 10000;
exports.DEFAULT_AI_SNAPSHOT_EFFICIENT_DEPTH = 6;
